[package]
name = "playbyte_emulation"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }

[dependencies]
playbyte_libretro = { path = "../playbyte_libretro" }
thiserror = "1.0"

[dev-dependencies]
sha1 = "0.10"